# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-12 10:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0062_auto_20180918_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='version',
            field=models.IntegerField(default=1, verbose_name='version'),
        ),
    ]
