# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-04-08 07:15
from __future__ import unicode_literals

import django.core.serializers.json
from django.db import migrations
import taiga.base.db.models.fields.json


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0063_game_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='roles',
            field=taiga.base.db.models.fields.json.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True),
        ),
    ]
