runtime: python37
service: taiga

handlers:
- url: /static
  static_dir: static/
- url: /api/v1
  script: auto
- url: /admin
  script: auto
- url: /v-1572609443890
  static_dir: dist/v-1572609443890
- url: /conf\.json
  static_files: dist/conf.json
  upload: dist/conf\.json
- url: /.*
  static_files: dist/index.html
  upload: dist/index\.html
